from datetime import datetime

from sqlmodel import Session, select

from app.models.entities import Artifact, Job, JobStatus, Project
from app.services.templates import TEMPLATES


def list_projects(session: Session):
    return session.exec(select(Project).order_by(Project.created_at.desc())).all()


def create_job(session: Session, job: Job) -> Job:
    session.add(job)
    session.commit()
    session.refresh(job)
    return job


def append_artifact(session: Session, job_id: int, artifact_type: str, title: str, content: str) -> Artifact:
    path = f"artifacts/job-{job_id}/{title.replace(' ', '-').lower()}.md"
    artifact = Artifact(job_id=job_id, artifact_type=artifact_type, title=title, path=path, content=content)
    session.add(artifact)

    db_job = session.get(Job, job_id)
    if db_job:
        db_job.updated_at = datetime.utcnow()
    session.commit()
    session.refresh(artifact)
    return artifact


def mark_job_status(session: Session, job_id: int, status: JobStatus) -> None:
    job = session.get(Job, job_id)
    if not job:
        return
    job.status = status
    job.updated_at = datetime.utcnow()
    session.add(job)
    session.commit()


def build_default_job_artifacts(job_type: str, project_name: str) -> list[tuple[str, str, str]]:
    if job_type == "codebase_analysis":
        return [
            ("markdown", "README-style overview", f"# {project_name} Overview\n\nGenerated by Forge."),
            ("markdown", "architecture", "# Architecture\n\n- Module map\n- Entry points\n- Risks"),
            ("markdown", "onboarding", "# Onboarding\n\n1. Setup\n2. Run\n3. Testing"),
        ]
    return [
        (
            "markdown",
            "job-output",
            f"# {job_type}\n\nTemplate `{TEMPLATES.get(job_type, {}).get('version', 'v1')}` executed.",
        )
    ]
